default_install_hook_types:
  - pre-commit
  - post-checkout
  - post-merge
  - post-rewrite

repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.9.3
    hooks:
      - id: uv-sync

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.9.3
    hooks:
      # Update the uv lockfile
      - id: uv-lock


  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.14.1
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/shyndman/unroot-llm-files-pre-commit
    rev: v0.0.8
    hooks:
      # Sets up symlinks after checkout/merge
      - id: setup-managed-symlinks
        args:
          - --hidden-dir=.aid
          - --files=AGENTS.md,CLAUDE.md

      # Validates symlinks during normal commits
      - id: check-managed-symlinks
        args:
          - --hidden-dir=.ai
          - --files=AGENTS.md,CLAUDE.md

      # Ensures .gitignore includes symlinked files
      - id: update-gitignore-for-symlinks
        args:
          - --hidden-dir=.ai
          - --files=AGENTS.md,CLAUDE.md
