default_install_hook_types:
  - pre-commit
  - post-checkout
  - post-merge
  - post-rewrite

repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.9.3
    hooks:
      - id: uv-sync
        name: Sync dependencies (uv sync)

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.9.3
    hooks:
      # Update the uv lockfile
      - id: uv-lock
        name: Ensure a current lockfile (uv lock)

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.14.1
    hooks:
      # Run the linter.
      - id: ruff-check
        name: Lint the codebase (ruff check --fix)
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
        name: Format the codebase (ruff format)

  - repo: https://github.com/shyndman/ai-deroot-pre-commit
    rev: v0.0.9
    hooks:
      - id: setup-managed-symlinks
        args: [--hidden-dir=.ai, '--files=CLAUDE.md,AGENTS.md,.claude', --migrate=move]
      - id: check-managed-symlinks
        args: [--hidden-dir=.ai, '--files=CLAUDE.md,AGENTS.md,.claude']
      - id: update-gitignore-for-symlinks
        args: [--hidden-dir=.ai, '--files=CLAUDE.md,AGENTS.md,.claude']

  - repo: local
    hooks:
      - id: forbid-path-sourced-dependencies
        name: Prevent path sourced dependencies in pyproject.toml
        entry: python scripts/pre-commit/check_no_path_dependencies.py
        language: python
        pass_filenames: false
      - id: ty
        name: Type-check the codebase (ty check)
        entry: uv run ty check
        language: python
